language: php
php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm
install:
  - composer install --prefer-source --no-interaction
script:
  - phpunit
  - vendor/bin/php-cs-fixer fix --dry-run
after_success:
  - ./codecov
